- name: disable pcscd
  service:
    name: pcscd
    enabled: no
    state: stopped

- name: mkdir /opt/chinachu
  file: dest=/opt/chinachu state=directory

- name: clone dockerfiles
  git:
    repo: https://github.com/Chinachu/docker-mirakurun-chinachu.git
    dest: /opt/chinachu/docker-mirakurun-chinachu
    accept_hostkey: yes

- name: copy mirakurun-chinachu.service
  template:
    src: mirakurun-chinachu.service.j2
    dest: /etc/systemd/system/mirakurun-chinachu.service
    mode: 0755

- name: enable mirakurun-chinachu
  systemd:
    name: mirakurun-chinachu
    enabled: yes

- name: copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/chinachu/docker-mirakurun-chinachu/docker-compose.yml
    mode: 0755

- name: copy Dockerfile
  template:
    src: Dockerfile-mirakurun.j2
    dest: /opt/chinachu/docker-mirakurun-chinachu/mirakurun/Dockerfile
    mode: 0755

- name: "chmod volumes: mirakurun/conf"
  file:
    path: /opt/chinachu/docker-mirakurun-chinachu/mirakurun/conf
    state: directory
    recurse: yes
    owner: nobody
    group: nobody
    mode: 0777

- name: "chmod volumes: mirakurun/db"
  file:
    path: /opt/chinachu/docker-mirakurun-chinachu/mirakurun/db
    state: directory
    recurse: yes
    owner: nobody
    group: nobody
    mode: 0777

- name: "chmod volumes: chinachu/conf"
  file:
    path: /opt/chinachu/docker-mirakurun-chinachu/chinachu/conf
    state: directory
    mode: 0777
    owner: nobody
    group: nobody
    recurse: yes

- name: "chmod volumes: chinachu/data"
  file:
    path: /opt/chinachu/docker-mirakurun-chinachu/chinachu/data
    state: directory
    mode: 0777
    owner: nobody
    group: nobody
    recurse: yes

- name: "chmod volumes: chinachu/recorded"
  file:
    path: /opt/chinachu/docker-mirakurun-chinachu/recorded
    state: directory
    mode: 0777
    owner: nobody
    group: nobody
    recurse: yes
