FROM node:8.9-alpine
LABEL maintainer "Shuma Yoshioka <s64.stdio@gmail.com>"

ENV DOCKER="YES"

RUN set -x \
	&& apk upgrade --update \
	&& apk add \
		bash \
		coreutils \
		libusb \
		pcsc-lite \
		pcsc-lite-libs \
		curl \
		ca-certificates \
		util-linux \
	\
	&& apk add --virtual .build-deps \
		git \
		make \
		gcc \
		g++ \
		gzip \
		autoconf \
		automake \
		libc-dev \
		musl-dev \
		eudev-dev \
		libevent-dev \
		pcsc-lite-dev \
		libusb-dev \
	\
	&& npm install pm2 -g \
	\
	&& npm install arib-b25-stream-test -g --unsafe \
	\
	# mirakurun
	&& npm install mirakurun@latest -g --unsafe --production \
	\
	# recpt1
	&& git clone https://github.com/stz2012/recpt1 /tmp/recpt1 \
	&& cd /tmp/recpt1/recpt1 \
	&& ./autogen.sh \
	&& ./configure \
	&& sed -i '/#include <sys\/msg.h>/d' recpt1core.h \
	&& sed -i -E 's!(#include <sys/msg.h>)!#undef _GNU_SOURCE\n#undef _BSD_SOURCE\n\1!' recpt1.c \
	&& sed -i -E 's!(#include <sys/msg.h>)!#undef _GNU_SOURCE\n#undef _BSD_SOURCE\n\1!' recpt1ctl.c \
	&& sed -i -E 's!(#include <sys/msg.h>)!#undef _GNU_SOURCE\n#undef _BSD_SOURCE\n\1!' checksignal.c \
	&& sed -i -E 's!(#include <ctype.h>)!\1\n#include <event.h>!' tssplitter_lite.c \
	&& sed -i 's#-I../driver#-I../driver -I/usr/local/include#' Makefile \
	&& make \
	&& make install \
	\
	# ccid
	&& cd /tmp \
	&& (curl -s https://alioth.debian.org/frs/download.php/file/4205/ccid-1.4.26.tar.bz2 -o ccid-latest.tar.bz2 || curl -s http://ftp.debian.org/debian/pool/main/c/ccid/ccid_1.4.26.orig.tar.bz2 -o ccid-latest.tar.bz2) \
	&& tar xvf ccid-*.tar.bz2 \
	&& cd ccid-* \
	&& ./configure \
	&& make \
	&& make install

#RUN set -x \
#	# arib25
#	&& curl -s http://hg.honeyplanet.jp/pt1/archive/c44e16dbb0e2.zip -o /tmp/c44e16dbb0e2.zip \
#	&& mkdir /tmp/arib25 \
#	&& unzip -n -d /tmp/arib25 /tmp/c44e16dbb0e2.zip \
#	&& cd /tmp/arib25/pt1-c44e16dbb0e2/arib25 \
#    && sed -i -e 's/ldconfig$/ldconfig \//' src/Makefile \
#	&& make \
#	&& make install

RUN set -x \
	# MyRecpt1 for PLEX (as recpx4)
	&& curl -s http://plex-net.co.jp/download/linux/Linux_Driver.zip -o /tmp/recpx4.zip \
	&& mkdir /tmp/recpx4 \
	&& unzip -n -d /tmp/recpx4 /tmp/recpx4.zip \
	&& cd /tmp/recpx4/Linux_Driver/MyRecpt1/MyRecpt1/recpt1 \
	&& install -m 755 recpt1 /usr/local/bin/recpx4 \
	&& install -m 755 recpt1ctl /usr/local/bin/recpx4ctl \
    && mkdir /lib64 \
    && ln -s /lib/ld-musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

#RUN set -x \
#    # recdvb
#    && curl -s http://www13.plala.or.jp/sat/recdvb/recdvb-1.2.0.tgz -o /tmp/recdvb.tgz \
#    && cd /tmp \
#    && tar xvzf recdvb.tgz \
#    && cd recdvb-1.2.0 \
#    && apk add --virtual .build-deps linux-headers \
#    && ./autogen.sh \
#    && ./configure \
#    && sed -i '/#include <sys\/msg.h>/d' recpt1core.h \
#	&& sed -i -E 's!(#include <sys/msg.h>)!#undef _GNU_SOURCE\n#undef _BSD_SOURCE\n\1!' recpt1.c \
#	&& sed -i -E 's!(#include <sys/msg.h>)!#undef _GNU_SOURCE\n#undef _BSD_SOURCE\n\1!' recpt1ctl.c \
#	&& sed -i -E 's!(#include <sys/msg.h>)!#undef _GNU_SOURCE\n#undef _BSD_SOURCE\n\1!' checksignal.c \
#	&& sed -i -E 's!(#include <ctype.h>)!\1\n#include <event.h>!' tssplitter_lite.c \
#    && make \
#    && make install

RUN set -x \
	# cleaning
	&& cd / \
	&& npm cache verify \
	&& apk del --purge .build-deps \
	#&& rm -rf /tmp/* \
	&& rm -rf /tmp/recpt1 \
	&& rm -rf /tmp/ccid-* \
	&& rm -rf /var/cache/apk/*

# RUN set -x \
	# forward request and error logs to docker log collector
	#&& ln -sf /dev/stdout /usr/local/var/log/mirakurun.stdout-0.log \
	#&& ln -sf /dev/stderr /usr/local/var/log/mirakurun.stderr-0.log

COPY services.sh /usr/local/bin/services.sh

WORKDIR /usr/local/lib/node_modules/mirakurun
CMD ["/usr/local/bin/services.sh"]
EXPOSE 40772
