- name: install pcsc-lite (yum)
  when: ansible_pkg_mgr == 'yum'
  action: "{{ansible_package_mgr}} name={{item}}"
  with_items:
    - pcsc-lite
    - pcsc-lite-devel
    - pcsc-lite-libs
    - ccid

- stat: path=/usr/bin/pcsc_scan
  register: pcsc_scan_binary

- name: download pcsc-perl (pcsc-perl-1.4.13.tar.bz2)
  get_url: url=http://ludovic.rousseau.free.fr/softwares/pcsc-perl/pcsc-perl-1.4.13.tar.bz2 dest=/tmp/pcsc_drivers/pcsc-perl-1.4.13.tar.bz2
  when: not pcsc_scan_binary.stat.exists

- name: unzip pcsc-perl
  shell: tar jxvf /tmp/pcsc_drivers/pcsc-perl-1.4.13.tar.bz2 -C /tmp/pcsc_drivers/
  when: not pcsc_scan_binary.stat.exists

- name: perl Makefile.PL (pcsc-perl)
  shell: perl Makefile.PL
  args:
    chdir: /tmp/pcsc_drivers/pcsc-perl-1.4.13
  when: not pcsc_scan_binary.stat.exists

- name: make pcsc-perl
  shell: make
  args:
    chdir: /tmp/pcsc_drivers/pcsc-perl-1.4.13
  when: not pcsc_scan_binary.stat.exists

- name: install pcsc-perl
  sudo_user: root
  shell: make install
  args:
    chdir: /tmp/pcsc_drivers/pcsc-perl-1.4.13
  when: not pcsc_scan_binary.stat.exists

- name: download pcsc-tools (pcsc-tools-1.4.23.tar.gz)
  get_url: url=http://ludovic.rousseau.free.fr/softwares/pcsc-tools/pcsc-tools-1.4.23.tar.gz dest=/tmp/pcsc_drivers/pcsc-tools-1.4.23.tar.gz
  when: not pcsc_scan_binary.stat.exists

- name: unzip pcsc-tools (pcsc-tools-1.4.23.tar.gz)
  shell: tar xvzf /tmp/pcsc_drivers/pcsc-tools-1.4.23.tar.gz -C /tmp/pcsc_drivers/
  when: not pcsc_scan_binary.stat.exists

- name: make pcsc-tools
  shell: make
  args:
    chdir: /tmp/pcsc_drivers/pcsc-tools-1.4.23
  when: not pcsc_scan_binary.stat.exists

- name: install pcsc-tools
  sudo_user: root
  shell: make install
  args:
    chdir: /tmp/pcsc_drivers/pcsc-tools-1.4.23
  when: not pcsc_scan_binary.stat.exists

- name: enable pcscd
  service: name=pcscd enabled=yes state=started

- name: download arib25 (c44e16dbb0e2.zip)
  get_url: url=http://hg.honeyplanet.jp/pt1/archive/c44e16dbb0e2.zip dest=/tmp/pcsc_drivers/c44e16dbb0e2.zip

- name: mkdir /tmp/pcsc_drivers/arib25
  file: dest=/tmp/pcsc_drivers/arib25 state=directory

- name: unzip arib25 (c44e16dbb0e2.zip)
  shell: unzip -n -d /tmp/pcsc_drivers/arib25 /tmp/pcsc_drivers/c44e16dbb0e2.zip

- name: make arib25
  shell: make
  args:
    chdir: /tmp/pcsc_drivers/arib25/pt1-c44e16dbb0e2/arib25

- name: install arib25
  sudo_user: root
  shell: make install
  args:
    chdir: /tmp/pcsc_drivers/arib25/pt1-c44e16dbb0e2/arib25
