- stat: path=/usr/lib64/tty_Virtual.ko
  register: ko_tty_Virtual

- name: download PLEX driver
  when: not ko_tty_Virtual.stat.exists
  get_url:
    url: http://plex-net.co.jp/plex/linux/CentOS7-1708_64bit_kernel3.10.0-693.zip

- name: unzip PLEX driver
  when: not ko_tty_Virtual.stat.exists
  shell: unzip -n -d /tmp /tmp/CentOS7-1708_64bit_kernel3.10.0-693.zip

- name: cp tty_Virtual.ko to /usr/lib64
  when: not ko_tty_Virtual.stat.exists
  shell: cp --update /tmp/CentOS7-1708_64bit_kernel3.10.0-693/tty_Virtual.ko /usr/lib64/tty_Virtual.ko

- name: cp usb-px4.ko to /usr/lib64
  when: not ko_tty_Virtual.stat.exists
  shell: cp --update /tmp/CentOS7-1708_64bit_kernel3.10.0-693/usb-px4.ko /usr/lib64/usb-px4.ko

- name: copy plex.modules
  template: >
    src=plex.modules.j2
    dest=/etc/sysconfig/modules/plex.modules
    owner=root
    group=root
    mode=0644
  when: not ko_tty_Virtual.stat.exists

- name: activate tty_Virtual.ko
  shell: insmod /usr/lib64/tty_Virtual.ko
  when: not ko_tty_Virtual.stat.exists

- name: activate usb-px4.ko
  shell: insmod /usr/lib64/usb-px4.ko
  when: not ko_tty_Virtual.stat.exists
