- name: add epel repo
  yum: "name={{item}}"
  with_items:
    - epel-release

- name: install yum utils
  yum: "name={{item}}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: install docker**-io** (for CentOS 6)
  yum: "name={{item}}"
  with_items:
    - docker-io

- name: enable docker
  service: name=docker enabled=yes state=started

- name: install pip
  yum: "name={{item}}"
  with_items:
    - pip

- name: install docker-compose
  shell: bash -lc "pip install -U docker-compose"
