- name: add epel repo
  yum: "name={{item}}"
  with_items:
    - epel-release

- name: install yum utils
  yum: "name={{item}}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: install docker**-io** (for CentOS 6)
  yum: "name={{item}}"
  with_items:
    - docker-io

- name: enable docker
  service: name=docker enabled=yes state=started

- name: install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755

- name: download glibc 2.14
  get_url:
    url: "http://ftp.gnu.org/gnu/glibc/glibc-2.14.tar.gz"
    dest: /tmp/glibc-2.14.tar.gz

- name: unzip glibc-2.14.tar.gz
  shell: tar zxvf /tmp/glibc-2.14.tar.gz
  args:
    chdir: /tmp/

- name: mkdir /tmp/glibc-2.14/build
  file: dest=/tmp/glibc-2.14/build state=directory

- name: configure glibc
  shell: /tmp/glibc-2.14/configure --prefix=/lib64
  args:
    chdir: /tmp/glibc-2.14/build

- name: make glibc
  shell: make -j4
  args:
    chdir: /tmp/glibc-2.14/build

- name: install glibc
  shell: make install
  args:
    chdir: /tmp/glibc-2.14/build
