- name: add epel repo
  yum: "name={{item}}"
  with_items:
    - epel-release

- name: install yum utils
  yum: "name={{item}}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: install docker**-io** (for CentOS 6)
  yum: "name={{item}}"
  with_items:
    - docker-io

- name: enable docker
  service: name=docker enabled=yes state=started

- name: install docker-compose
  get_url: url=https://github.com/docker/compose/releases/download/1.20.1/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose mode=0755
